project:
  type: website

website:
  title: "Semantics Reading Group"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: meetings.qmd
        text: Meetings
      - href: materials.qmd
        text: Materials & Book
      - href: exercises.qmd
        text: Exercises

format:
  html:
    theme: cosmo
    toc: true